{
 "title": "Raspberry Pi Cluster Operations Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg((avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100))",
     "legendFormat": "Average CPU Usage"
    }
   ]
  },
  {
   "title": "Average Cluster Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[5m]) + avg_over_time(node_memory_Cached_bytes[5m]) + avg_over_time(node_memory_Buffers_bytes[5m])) / avg_over_time(node_memory_MemTotal_bytes[5m]))))",
     "legendFormat": "Average Memory Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Transmit"
    }
   ]
  },
  {
   "title": "Cluster Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - RPI41",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.188.30:9100\"}[5m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage - RPi51",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.188.35:9100\"}[5m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage - RPi52",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.188.39:9100\"}[5m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage - RPi53",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.188.38:9100\"}[5m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage - RPi54",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.188.32:9100\"}[5m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Disk- rpi41",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"192.168.188.32:9100\"}/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory - rpi41",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"192.168.188.30:9100\"}/(1024*1024))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory - rpi51",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"192.168.188.35:9100\"}/(1024*1024))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory-rpi52",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"192.168.188.39:9100\"}/(1024*1024))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory-rpi53",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"192.168.188.38:9100\"}/(1024*1024))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory-rpi54",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=\"192.168.188.32:9100\"}/(1024*1024))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - rpi41",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\", instance=\"192.168.188.32:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - rpi51",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\", instance=\"192.168.188.35:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - rpi52",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\", instance=\"192.168.188.39:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - rpi53",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\", instance=\"192.168.188.38:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature - rpi54",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\", instance=\"192.168.188.32:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk- rpi51",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"192.168.188.35:9100\"}/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk- rpi52",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"192.168.188.39:9100\"}/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk- rpi53",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"192.168.188.38:9100\"}/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk- rpi54",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=\"192.168.188.32:9100\"}/(1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic - $node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\"}[5m])",
       "legendFormat": "{{device}} Receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\"}[5m])",
       "legendFormat": "{{device}} Transmit"
      }
     ]
    },
    {
     "title": "Disk Usage - $node",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",mountpoint=\"/\"})",
       "legendFormat": "Disk Usage"
      }
     ]
    }
   ]
  }
 ]
}